language: cpp
compiler:
  - gcc
  - clang
install:
  - sudo apt-get update -qq
  - ./install-deps --with-included-boost
  - ./tools/include-boost-src
before_script: ./bootstrap
script: ./configure --with-included-boost && make
