#  .travis.yml -- Continuous Integration configuration
#  Copyright (C) 2014-2016  Olaf Meeuwissen
#
#  License: GPL-3.0+
#  Author : Olaf Meeuwissen
#
#  This file is part of the 'Utsushi' package.
#  This package is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License or, at
#  your option, any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#  You ought to have received a copy of the GNU General Public License
#  along with this package.  If not, see <http://www.gnu.org/licenses/>.

sudo: required
dist: trusty
language: cpp
services:
  - docker
compiler:
  - gcc
  - clang
install:
  - sudo apt-get update -qq
  - ./install-deps
before_script:
  - docker pull debian:stable
  - docker run -v `pwd`:/home -w /home debian:stable /bin/sh -c 'apt-get -qq update && apt-get install -qqy --no-install-recommends autoconf autoconf-archive automake autopoint libltdl-dev libtool gnulib patch pkg-config && ./bootstrap'
  - sudo chown --recursive `id -u`:`id -g` .
script: ./configure && make -j2
